### ISSUE TITLE
Permission denied when running as a docker container

### ISSUE THREAD

**Issue by ryanMeredith** [Lusitaniae/phpfpm_exporter#20]
Docker log error

Failed to scrape socket: dial unix /run/php/php7.2-fpm.sock: connect: permission denied

Path is correct but I cannot read data

**Comment by Lusitaniae** [comment]
Did you mount the sock into the docker container?

Example from readme
```
SOCK="/run/php/php7.2-fpm.sock"; \
docker run -d -p 9253:9253 -v $SOCK:$SOCK  \
lusotycoon/phpfpm-exporter \
--phpfpm.socket-paths=$SOCK
```

**Comment by ryanMeredith** [comment]
I ran exactly the example from the readme, sorry I don't have any other debug info

**Comment by Lusitaniae** [comment]
is php-fpm serving the status page?

please try to download the binary and run it directly against the php-fpm host instead of using another container

**Comment by ryanMeredith** [comment]
I can get to the status page via browser, I will try the binary directly. Thanks

**Comment by ryanMeredith** [comment]
OK, the binary doesn't throw the permission error but it returns the same info in /metric with or without the error

# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0
go_gc_duration_seconds_sum 0
go_gc_duration_seconds_count 0
.....

**Comment by ryanMeredith** [comment]
I am getting permissions issues when running https://github.com/hipages/php-fpm_exporter on 127.0.0.1:9000 so safe to say I am the problem not your code.

Thanks for your help.
